/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowgestion (void);
GtkWidget* create_AfficherTroupeau (void);
GtkWidget* create_ModifierTroupeau (void);
GtkWidget* create_AjouterTroupeau (void);
GtkWidget* create_NombreTroupeau (void);
GtkWidget* create_bwafficher (void);
GtkWidget* create_bwajout (void);
GtkWidget* create_bwUpdate (void);
GtkWidget* create_bwcapteur (void);
GtkWidget* create_Afficherplante (void);
GtkWidget* create_Ajoutplante (void);
GtkWidget* create_Updateplante (void);
GtkWidget* create_dashbord (void);
GtkWidget* create_LOGIN (void);
GtkWidget* create_SIGN_IN (void);
GtkWidget* create_ccafficher (void);
GtkWidget* create_ccajout (void);
GtkWidget* create_ccUpdate (void);
GtkWidget* create_Ajout_capteurs (void);
GtkWidget* create_Gestion_capteurs (void);
GtkWidget* create_Modification (void);
GtkWidget* create_Affichage (void);
GtkWidget* create_tache2hamza (void);
GtkWidget* create_logindashbord (void);
GtkWidget* create_AfficherOuvrier (void);
GtkWidget* create_AjoutOuvrier (void);
GtkWidget* create_UpdateOuvrier (void);
GtkWidget* create_AjoutAbscence (void);
GtkWidget* create_ModifierAbs (void);
GtkWidget* create_AfficherAbs (void);
GtkWidget* create_TauxAbs (void);
GtkWidget* create_Tache2youssef1 (void);
GtkWidget* create_meilleurouvrier (void);
